### ISSUE TITLE
打开发现还有个控制台，你的打包方式是不是有问题？

### ISSUE THREAD

**Issue by Femtometer** [XIVN1987/JSVDView#1]
![截屏_2021-04-15_18-04-43](https://user-images.githubusercontent.com/5461891/114857747-37a81500-9e1b-11eb-9afa-12f40ccb3f7d.png)

**Comment by Femtometer** [comment]
每次刷新都要选择一次芯片型号：
![截屏_2021-04-15_19-04-29](https://user-images.githubusercontent.com/5461891/114859555-7e970a00-9e1d-11eb-9437-fbb4d6f84dc8.png)

**Comment by XIVN1987** [comment]
已更新，你试下。。
